# Generated by Django 3.0.4 on 2020-03-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.IntegerField(choices=[('Answer 1', 1), ('Answer 2', 2), ('Answer 3', 3), ('Answer 4', 4)], default=1),
            preserve_default=False,
        ),
    ]
