# Generated by Django 3.0.4 on 2020-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')]),
        ),
    ]
