# Generated by Django 3.0.2 on 2020-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, unique=True)),
                ('toolkit', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
    ]
