# Generated by Django 3.0.4 on 2020-03-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap', '0002_toolkit_content'),
        ('save_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_scrap.Toolkit'),
        ),
    ]
