# Generated by Django 3.0.4 on 2020-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_questions', '0002_auto_20200310_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=256),
        ),
    ]
